### ISSUE TITLE
LICENSE情報がない

### ISSUE THREAD

**Issue by ykinoshi1015** [tYoshiyuki/trx-converter#1]
ぜひ利用させていただきたいので、LICENSE情報を追加していただけないでしょうか。
（LICENSE情報がないと、利用できないため）

**Comment by tYoshiyuki** [comment]
返答が遅くなってしまい、大変申し訳ございません！
ライセンス情報を追加しましたので、ご確認ください。

**Comment by ykinoshi1015** [comment]
ありがとうございます、助かりました！
